/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2023-03-29 08:08:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import openGaussPlatform.openGausslink;
import java.sql.Connection;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("openGaussPlatform.openGausslink");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>openGauss学习平台</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body\r\n");
      out.write("{\r\n");
      out.write("    background-image:url(\"背景1.jpg\");\r\n");
      out.write("    background-size:cover;  \r\n");
      out.write("}\r\n");
      out.write(" a\r\n");
      out.write("      {\r\n");
      out.write("        text-decoration:none;\r\n");
      out.write("        background-color: #DBDBDB;\r\n");
      out.write("        border:1.5px solid #DBDBDB;\r\n");
      out.write("        margin-left:12px;\r\n");
      out.write("        color:black;\r\n");
      out.write("        height:25px;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("      }\r\n");
      out.write("      .type1\r\n");
      out.write("      {\r\n");
      out.write("        background-color:#DBDBDB;\r\n");
      out.write("        border:1.5px solid #DBDBDB;\r\n");
      out.write("        height:25px;\r\n");
      out.write("      }\r\n");
      out.write("     input\r\n");
      out.write("          {\r\n");
      out.write("            margin-top:20px;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("          }\r\n");
      out.write("     input:hover\r\n");
      out.write("          {\r\n");
      out.write("            background-color: #33FF33;\r\n");
      out.write("          }\r\n");
      out.write("     a:hover\r\n");
      out.write("          {\r\n");
      out.write("            background-color: #33FF33;\r\n");
      out.write("          }\r\n");
      out.write("     .box{\r\n");
      out.write("width: 1400px;\r\n");
      out.write("\r\n");
      out.write("height: 600px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".left-box{\r\n");
      out.write("width:60%;\r\n");
      out.write("height:80%;\r\n");
      out.write("float: left;\r\n");
      out.write("overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right-box{\r\n");
      out.write("width:20%;\r\n");
      out.write("height:50%;\r\n");
      out.write("float: right;\r\n");
      out.write("margin-top:90px;\r\n");
      out.write("border: 2px solid #a1a1a1;\r\n");
      out.write("border-radius: 25px;\r\n");
      out.write("}\r\n");
      out.write(".imgBox{\r\n");
      out.write("            \r\n");
      out.write("            width: 9999px;\r\n");
      out.write("            height:100%;\r\n");
      out.write("            animation:switch 15s infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .imgBox img{\r\n");
      out.write("            float: left;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("@keyframes switch{\r\n");
      out.write("\t\t0%{};\r\n");
      out.write("\t\t25%{transform:translateX(0px);}\r\n");
      out.write("\t\t50%{transform:translateX(-840px);}\r\n");
      out.write("\t\t75%{transform:translateX(-1680px);}\r\n");
      out.write("\t\t100%{transform:translateX(-2520px);}\r\n");
      out.write("\t\t}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("<img src=\"img4.png\">\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("<div class=\"left-box\">\r\n");
      out.write("<div class=\"imgBox\">\r\n");
      out.write("    <img src=\"img3.jpg\">\r\n");
      out.write("    <img src=\"img1.jpg\">\r\n");
      out.write("    <img src=\"img2.jpg\">\r\n");
      out.write("    <img src=\"img3.jpg\">\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"right-box\">\r\n");
      out.write("<form action=\"login_yanzheng\">\r\n");
 session.setAttribute("存在", 0); 
      out.write("\r\n");
      out.write(" <center style=\"font-size:25px;\">欢迎登录系统</center><br><br>\r\n");
      out.write("      <center>\r\n");
      out.write("      <input type=\"text\" placeholder=\"学号\" name=\"code\">\r\n");
      out.write("      <br>\r\n");
      out.write("      <input type=\"password\" placeholder=\"密码\" name=\"pass\"><br><br>\r\n");
      out.write("       <input type=\"submit\" value=\"登录\" class=\"type1\">\r\n");
      out.write("      <input type=\"button\" value=\"注册\" onclick=\"window.location.href='zhuce.jsp'\">\r\n");
      out.write("      </center>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
